### PR TITLE
Fix BR-CO-10 invalid xpath

### PR DESCRIPTION
**Pull request by dbkosky**
I don't see any contribution guidelines, but I figured I'd give it a shot.

As far as I can see `//(cac:InvoiceLine|cac:CreditNoteLine)` does not seem to be valid xpath syntax.
So I've replaced it with `(//cac:InvoiceLine|//cac:CreditNoteLine)`, which seems to fulfill the intended purpose.

Subsequently, the `xs:decimal(cbc:LineExtensionAmount)`  is not valid, and is thus removed

I've changed all the occurrences that I could find, please let me know if I'm wrong :slightly_smiling_face:

### CODE REVIEW

**Comment by phax** [comment]
An XPath expression in the form `//(a|b)` is totaly valid imho. See https://www.w3.org/TR/xpath20/#id-primary-expressions
What engine are you using that causes an error? Are you using Saxon? If so, what version?

**Comment by dbkosky** [comment]
Hello!
Im not using saxon. For various reasons the implementation I'm working on is limited to using python and `lxml`, applying each of the schematron's tests against each document.

So when using an `lxml` evaluator on this expression, it returns an Invalid Expression error.

**Comment by phax** [comment]
Hmmm - I think we have an implementation specific issue here...
I don't know if `//(a|b)` is the same as `(//a|//b)` in all cases.
However the case to "xs:decimal" is crucial to get decimal numbers right.
Eventually `lxml` (I don't know it) needs to be considered not compatible....???

**Comment by MartinForsberg-Ecru** [comment]
Could it be that lxml doesn't support XSLT v2 (and XPATH v2)? It looks like that could be the issue: https://lxml.de/xpathxslt.html

The xpath //(a|b) is not supported in XPATH v1. (and we have many other cases where we use features from XPATH v2.

**Comment by KbraBass** [comment]
Yeah, libxml2, used by lxml, does not support XPath 2.0. It supports some EXSLT and SAX modules on top of XPath 1.0.

You may want to use saxonpy instead https://pypi.org/project/saxonpy/

**Comment by dbkosky** [comment]
I've tested further and it is indeed down to the differences between XPath 1.0 and XPath 2.0 
(I was able to test with the `elementpath` python module using an XPath 1.0 and XPath 2.0 parser)

Thank you all for your help and suggestions :slightly_smiling_face: 
On that, I'll close this PR

**Pull request closed without merging**
